# Generated by Django 5.1.7 on 2025-03-09 13:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=300)),
                ('company', models.CharField(blank=True, max_length=300, null=True)),
                ('position_in_company', models.CharField(blank=True, max_length=300, null=True)),
                ('video', models.FileField(upload_to='testimonials/')),
                ('rating', models.SmallIntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
